image: maven:3-jdk-8

stages:
  - compile
  - test
  - build
  
compile:
  stage: compile
  script: "mvn clean compile"

test:
  stage: test
  script: 
  - "mvn test"
  - "cat target/site/jacoco/index.html"

build:
  stage: build
  script: "mvn package shade:shade"
